# !-------------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of ${project.artifactId}
# !-------------------------------------------------------------------------------------------------!
#
#    For support and documentation, please visit:
#    - https://github.com/kangarko/${project.artifactId}/wiki
#
# !-------------------------------------------------------------------------------------------------!
#
#    1) COLOR CODES are supported with the '&' character. See
#       - http://minecraftwiki.net/wiki/Formatting_codes
#       [!] When you use them, omit the message with " " or ' '.
#
#    2) TO HIDE a message, set it to 'none'.
#
#    3) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding. See
#       - https://github.com/kangarko/${project.artifactId}/wiki/Use-Right-Encoding
#
#    4) SOUND NAMES had changed as per Minecraft 1.9, compare:
#       - 1.9 and newer: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
#       - 1.8 and older: https://goo.gl/ArzbZA
#
#    PS: The information above applies for all files within the ${project.artifactId} folder.
#
# !-------------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------
# Settings for spawning Bosses using the Boss eggs. Get them via "/boss egg"
# -------------------------------------------------------------------------------------------
Egg_Spawning:
  #
  # How farthest away from the player to spawn when they right click a Boss egg?
  #
  Max_Distance: 60
  #
  # Spawn on right clicking the air?
  # Bosses will be spawned at the Max_Distance's blocks away from the player in the air!
  #
  Air_Spawn: true
  #
  # Still spawn the Boss even if right-clicking with Egg was prevented by something else?
  #
  # When on false, Air_Spawn may break.
  # When on true, eggs can be used in regions where not supposed to (where spawning is disabled).
  #
  Spawn_If_Event_Cancelled: true
  #
  # Only allow spawning if the Boss is inside his allowed spawning regions (see his menu -> Spawning -> Regions).
  # If you do not have any regions set up, Boss spawns everywhere.
  #
  Check_Regions: false
  #
  # Only allow spawning if the egg matches the latest Boss egg as configure in the menu?
  # If you make any changes to the egg, all old eggs in players' inventory will no longer function.
  #
  Enforce_Latest_Egg_Version: false
  #
  # Customize the Spawner Egg.
  #
  # If the material is MONSTER_EGG, it will be dynamically changed to the Boss type.
  #
  Item:
    Name: "&rSpawn {boss}"
    Material: MONSTER_EGG
    Glow: true
    Lore:
      - " "
      - "&2&l< &7Left click for menu"
      - "&2&l> &7Right click to summon"


# -------------------------------------------------------------------------------------------
# Spawn extra Bosses around players when they least expect them!
#
# This works even when you have natural monster spawning disabled on your server.
# -------------------------------------------------------------------------------------------
Timed_Spawning:
  #
  # Turn this feature on?
  #
  Enabled: true
  #
  # Strike a lightning when the boss is spawned?
  #
  Lightning: true
  #
  # How often should the timer try to spawn Bosses? Minimum is 1 second.
  #
  # Very low values such as 5 seconds *WILL* affect performance!
  #
  Delay: 90 seconds
  #
  # Settings that, when disabled or on low values, improve performance.
  #
  Performance:
    #
    # Respect spawn conditions for Bosses? You'll find them in Boss' Spawning menu.
    #
    Check_Conditions: true
    #
    # Check regions from /boss rg, WorldGuard, Residence etc.? The more you have the bigger the performance penaulty.
    #
    Check_Regions: true
    #
    # How many chunks around the player to scan?
    # Set to lowest possible number as this will affect your performance
    # 1 = 9 chunks, 2 = 25 chunks, 3 = 49 chunks (a lot!)
    #
    Chunk_Radius: 2
    #
    # Spawn Bosses in caves, buildings with roofs etc.?
    #
    Spawn_Underground: true

  #
  # In which worlds should the timer function? Set to Worlds: ["*"] to all worlds.
  #
  Worlds:
    - "*"
    
  #
  # Which Bosses should be spawned? Set to Bosses: ["*"] for all Bosses.
  #
  Bosses:
    - "*"

# -------------------------------------------------------------------------------------------
# When a monster spawns naturally in the night, Boss can convert it to a monster!
# -------------------------------------------------------------------------------------------
Converting:
  #
  # Should monsters naturally spawned be converted into Bosses?
  # THIS ONLY HAPPENS WHEN THE CONDITIONS YOU SPECIFY IN BOSS' SPAWNING MENU ARE MET.
  #
  Enabled: true
  #
  # Strike a lightning when the boss is spawned naturally?
  #
  Lightning: true
  #
  # Specify in what scenarious we should not convert the monster to Boss at all.
  #
  # Use the causes from the list below:
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  #
  Ignore_From: [SPAWNER]

# -------------------------------------------------------------------------------------------
# Completely prevent any and all vanilla mobs to spawn except those spawned using
# Timed Spawning, Boss Eggs and /boss spawn command?
#
# *WARNING* This completely prevents any mobs from spawning naturally,
#           including mobs from mob spawners etc. It's basically like a mob blocker plugin.
# -------------------------------------------------------------------------------------------
Prevent_Vanilla_Mobs:
  #
  # Enabled this feature?
  #
  Enabled: false
  #
  # Spawn reasons to prevent spawning, see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  #
  Prevent_From: [NATURAL, CHUNK_GEN, SPAWNER, VILLAGE_DEFENSE, VILLAGE_INVASION, REINFORCEMENTS, INFECTION, CURED, DROWNED]
  #
  # Prevent the following mobs from spawning (applies to Prevent_From causes above)
  #
  # Leave to ["*"] to prevent all of them, or simply specific their name (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html)
  # for example: Prevent_Mobs: [PHANTOM]
  #
  Entities: ["*"]
  #
  # List of worlds where to apply this limitation. Leave on * to apply on all worlds.
  # Requires Enabled to true.
  #
  Worlds: ["*"]

# -------------------------------------------------------------------------------------------
# How many Bosses can spawn in one place? Applies for Converting and Timed_Spawning.
#
# You can still spawn as many as you please with the Boss Egg ("/boss egg").
# Remember, a chunk is approximately the area around player, it is 16*256*16 blocks.
#
# IF YOU HAVE ANY PROBLEMS, SET Debug to ["spawning"] (BELOW) AND SEE WHAT HAPPENS IN THE
# GAME, BEFORE YOU REPORT ISSUES.
# -------------------------------------------------------------------------------------------
Limits:
  #
  # Should we also apply limit when Boss is spawned by /boss spawn ?
  #
  Apply_For_Commands: false
  #
  # Should we also apply limit when Boss is spawned by a Boss Egg ?
  #
  Apply_For_Eggs: false
  #
  # Apply limits for Bosses spawned after a Boss dies if reinforcements are set?
  #
  Apply_For_Reinforcements: false
  #
  # Apply limits and conditions for mob spawners?
  #
  Apply_For_Spawners: false
  #
  # Sets the radius to check other Bosses nearby another Boss for Radius_Limit options below.
  #
  Radius_Blocks: 64
  #
  # Applied for all bosses, e.g.: you can limit absolute all Bosses to 10 per chunk maximum.
  #
  Global:
    #
    # We recommend you leave global limits enabled, however if you are only spawning Bosses in regions
    # you can disable this. You will see a performance increase when both global and individual limits are disabled.
    #
    Enabled: true
    #
    # The maximum amount of any Bosses all together in the Radius_Blocks above
    #
    Radius_Limit: 32
    #
    # The maximum amount of Bosses per world.
    #
    World: 3000
  #
  # Applied for Bosses of same name.
  #
  Individual:
    #
    # Scan for Bosses of the same kind? Requires some math, affects perfomance on big worlds.
    #
    Enabled: false
    #
    # The maximum amount of the same Bosses in the Radius_Blocks above
    #
    Radius_Limit: 24
    #
    # The maximum amount of one kind of Boss per world.
    #
    World: 1000

# -------------------------------------------------------------------------------------------
# Controls keeping your Bosses within your Boss regions.
#
# How it works: You need to enable "Keep Inside" settings of a region. Once a Boss is spawned
# within it, we will mark him with a special sign.
#
# We search through all Bosses marked with those signs and teleport them to the closest
# region location when they escape the border.
# -------------------------------------------------------------------------------------------
Region_Keeping:
  #
  # Enable this feature? This will launch a repetitive task inside of Boss.
  #
  Enabled: true

  #
  # If enabled the boss will be teleported to the center of the region
  # instead of a few blocks back.
  #
  Port_To_Center: false

  #
  # How often to check and teleport Bosses back? Lower values may produce more lag.
  # 20 ticks = 1 second
  #
  Period: 20 ticks

# -------------------------------------------------------------------------------------------
# Options related to when you fight the Boss.
# -------------------------------------------------------------------------------------------
Fight:
  #
  # Display the health of the Boss in action bar?
  #
  Health_Bar: true
  #
  # Should we automatically find another entity for the Boss to attack after some time?
  # You can enable/disable this individually per-boss in his Specific Settings. Disabled by default.
  #
  Auto_Target: 
    #
    # Should we force the Boss to forget its old target and get a new one when being attacked by it?
    #
    Override_On_Attack: false
    #
    # Should Bosses find other non-Boss creatures to attack?
    #
    Creatures: true
    #
    # Should Bosses find players to attack?
    #
    Players: true
    #
    # Set the delay (ticks, seconds, minutes). Low values impact performance.
    #
    Delay: 10 seconds
    #
    # How many blocks around the Boss to look for entities? Large values impact performance.
    #
    Radius: 15

Death:
  #
  # Shall we run the "Death by player" command for the last X players who killed
  # the boss with their permissions?
  #
  # If false, we run the commands for them with console (OP) permissions.
  #
  Run_Player_Commands_As_Player: true

# -------------------------------------------------------------------------------------------
# Options related to the in-game configuration of Boss and their creation.
#
# *NOTE* Reloading is not supported if you make any chances here - restart your server!
# -------------------------------------------------------------------------------------------
Setup:
  #
  # Visualize selected regions with the tools in /boss tools?
  #
  # Since we listen each time each player changes their slot in the inventory,
  # performance may get affected on large servers. Disable to improve it.
  #
  Visualize_Regions: true
  #
  # Enable ProtocolLib integration to allow remapping sounds?
  #
  Hook_ProtocolLib: true
  #
  # Shall we sort your bosses in the GUI alphabetically?
  #
  Sort_Bosses_In_Menu_Alphabetically: false

# -------------------------------------------------------------------------------------------
# If false, when using Timed Spawn or Converting, we only randomly select 1 Boss of the
# same entity type and try to spawn it. If that fails, no Boss is spawned. When true,
# we iterate through all Bosses of the same entity type (can have a performance impact).
# -------------------------------------------------------------------------------------------
Iterate_Spawning_Tries: false

# -------------------------------------------------------------------------------------------
# Aliases are alternative command names which trigger the same command as the main command.
# Separate them with a comma, e.g: aliases: [boss, b]
# * THE FIRST ALIAS IS THE MAIN LABEL, THAT MEANS AT LEAST ONE ALIAS MUST BE SPECIFIED. *
# -------------------------------------------------------------------------------------------
Command_Aliases: [boss, b]

# -------------------------------------------------------------------------------------------
# You can change the prefix in front of chat or console messages here:
# -------------------------------------------------------------------------------------------
Prefix: "&8&lBOSS &8//&7"

# -------------------------------------------------------------------------------------------
# Change the language of the messages in this plugin, or completelly customize them.
# To customize, create localization/ folder and restart. A new file will appear there.
#
# Currently: en (English), cn (Chinese), it (Italian), es (Spanish), hu (Hungarian)
#            and ru (Russian)
# -------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------
# Should Boss check for new versions on startup and notify you in-game?
# -------------------------------------------------------------------------------------------
Notify_Updates: true

# -------------------------------------------------------------------------------------------
# Support the developer of this plugin to allow occasional promotional messages ?
# I promise to keep it low key and only display it once a day at maximum.
# -------------------------------------------------------------------------------------------
Notify_Promotions: true

# -------------------------------------------------------------------------------------------
# Time of some plugin's operations is measured. Print a message to the console if they take
# over the specified amount of time in milliseconds. Set to -1 to disable.
# -------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------
# Debugging allows you to understand the plugin. It will print more messages to the console.
# Specify sections to debug, or ["*"] to print all out.
# Available: ["spawning"]
# -------------------------------------------------------------------------------------------
Debug: []

# Internal serialization, do not touch
Serialization: ""

# Internal configuration number, do not touch :)
Version: 8